/*
 *	PDCVALUE.h
 *	Photron Device Control SDK
 *	Value Definition
 *
 *	Copyright (C) 2006-2012 PHOTRON LIMITED
 */

#ifndef	_PDC_VALUE_H_
#define	_PDC_VALUE_H_

/*	General	*/
#define	PDC_MAX_DEVICE			64		/*	Maximum connection devices	*/
#define	PDC_MAX_INTERFACE_TYPE	10		/*	Maximum interface type	*/
#define	PDC_MAX_DEVICE_TYPE		64		/*	Maximum device type	*/
#define	PDC_MAX_CHILD_DEVICE	4		/*	Maximum child devices	*/
#define	PDC_MAX_PARTITION		128		/*	Maximum partitions	*/
#define	PDC_MAX_LIST_NUMBER		256		/*	Maximum list parameters	*/
#define	PDC_MAX_STRING_LENGTH	256		/*	Maximum strings	*/
#define	PDC_MAX_LUTLIST_NUMBER	4096	/*	Maximum LUT list parameters	*/

/*	Function On/Off(General)	*/
#define	PDC_FUNCTION_OFF					0
#define	PDC_FUNCTION_ON						1
#define	PDC_FUNCTION_SOFT_ON				2

/*	Function presence	*/
#define	PDC_EXIST_NOTSUPPORTED				0
#define	PDC_EXIST_SUPPORTED					1

#define	PDC_EXIST_SENSOR_GAIN				2
#define	PDC_EXIST_SENSOR_GAMMA				3
#define	PDC_EXIST_COLORTEMP					4
#define	PDC_EXIST_DSSHUTTER					5
#define	PDC_EXIST_LUT						6
#define	PDC_EXIST_SHADING					7
#define	PDC_EXIST_II						8
#define	PDC_EXIST_EDGE_ENHANCE				9
#define	PDC_EXIST_VIDEO_OUT					10
#define	PDC_EXIST_SHUTTERLOCK				11
#define	PDC_EXIST_PARTITIONINC				12
#define	PDC_EXIST_HEADEXCHANGE				13
#define	PDC_EXIST_KEYLOCK					14
#define	PDC_EXIST_IRIG						15
#define	PDC_EXIST_MCDL						16
#define	PDC_EXIST_FRAME_ZERO				17
#define	PDC_EXIST_PIXELGAIN					18
#define	PDC_EXIST_COLOR_ENHANCE				19
#define	PDC_EXIST_AUTO_EXPOSURE				20
#define	PDC_EXIST_DELAY						21
#define	PDC_EXIST_DOWNLOAD_MODE				22
#define	PDC_EXIST_VARIABLE_FUNCTION			23
#define	PDC_EXIST_LOWLIGHT_MODE				24
#define	PDC_EXIST_PROGSWITCH_MODE			25
#define	PDC_EXIST_SHUTTERSPEED_USEC			26
#define	PDC_EXIST_SYNCOUT_TIMES				27
#define	PDC_EXIST_STORE						28
#define	PDC_EXIST_ETHER_INFO				29
#define	PDC_EXIST_IRIG_PHASELOCK			30
#define	PDC_EXIST_HIGH_SPEED_MODE			31
#define	PDC_EXIST_BURST_TRANSFER			32
#define	PDC_EXIST_STEP_SHUTTER				33
#define PDC_EXIST_LIVE_RESOLUTION			34
#define	PDC_EXIST_BITDEPTH					35
#define	PDC_EXIST_FPGA_SETTING				36
#define	PDC_EXIST_CAMERA_DEF_FILE			37
#define	PDC_EXIST_IMAGE_ADDRESS				38
#define	PDC_EXIST_SYNC_PRIORITY				39
#define	PDC_EXIST_ROI						40
#define	PDC_EXIST_CAMERA_COMMAND			41
#define	PDC_EXIST_VIDEO_SIGNAL				42
#define	PDC_EXIST_VIDEO_HDSDI				43
#define	PDC_EXIST_RECORDING_TYPE			44
#define	PDC_EXIST_GHOST_REDUCTION			45
#define	PDC_EXIST_SOFT_COLORTEMP			46
#define	PDC_EXIST_AUTO_PLAY					47
#define	PDC_EXIST_FACTORY_DEFAULTS			48
#define	PDC_EXIST_STORE_PRESET				49
#define	PDC_EXIST_SHUTTERSPEED_NSEC			50
#define PDC_EXIST_INSTRUCTIONSET			51
#define	PDC_EXIST_RESOLUTIONLOCK			52
#define PDC_EXIST_LED_MODE					53
#define PDC_EXIST_LIVE_IRIG					54
#define	PDC_EXIST_VIDEO_OSD					55
#define PDC_EXIST_SENSOR_TEMP				56
#define	PDC_EXIST_SHADING_OFFSET			57
#define	PDC_EXIST_MEMORY_BLOCK				58
#define	PDC_EXIST_LIVE_RESOLUTION_SCALE		59
#define	PDC_EXIST_FRAME_ADDRESS				60
#define	PDC_EXIST_DROP_FRAME				61
#define	PDC_EXIST_TEST_PATERN				62
#define	PDC_EXIST_OFFSET_AS					63
#define	PDC_EXIST_H_BANDING					64
#define PDC_EXIST_KEYPAD_COMMAND			65
#define	PDC_EXIST_POLARIZATION				66
#define	PDC_EXIST_SHADING_TYPE				67
#define	PDC_EXIST_BLACK_CLIP_LEVEL			68
#define	PDC_EXIST_BITDEPTH2					69
#define	PDC_EXIST_SUB_PORT					70
#define	PDC_EXIST_SUB_INTERFACE				71
#define	PDC_EXIST_EXPOSE_EXTENSION			72
#define PDC_EXIST_BATTERY_POWERMODE			73
#define PDC_EXIST_SYNCIN_SIGNAL_STATUS		74
#define PDC_EXIST_VFPN_DATA					75
#define PDC_EXIST_SENSORLUT_DATA			76
#define PDC_EXIST_FPGA_TEMP					77
#define PDC_EXIST_DELAY_TRIG_MASK_WIDTH		78
#define PDC_EXIST_DELAY_VSYNC_MASK_WIDTH	79
#define PDC_EXIST_BINNING_SENSORMODE		80
#define	PDC_EXIST_EXPOSEOUT_TIMES			81
#define	PDC_EXIST_REC_EXPOSEOUT_TIMES		82
#define	PDC_EXIST_IMAGE_TRIGGER				83
#define	PDC_EXIST_LENS_CONTROL				84
#define	PDC_EXIST_RTC						85
#define	PDC_EXIST_MEMORYMODE_PARTITION		86
#define PDC_EXIST_FIX_FRAMERECORDMODE		87
#define PDC_EXIST_GETHER_TRANSFER_MODE		88
#define PDC_EXIST_MECHASHUTTER_MODE			89
#define PDC_EXIST_EXPOSETIME_DATA			90
#define	PDC_EXIST_FAN_CTRL					91
#define	PDC_EXIST_SD_CARD_CTRL				92
#define PDC_EXIST_STRADDLING_SIGNAL			93

/*	Color / Monochrome	*/
#define	PDC_COLORTYPE_MONO					0
#define	PDC_COLORTYPE_COLOR					1

/*	Status	*/
#define	PDC_STATUS_LIVE						0x00
#define	PDC_STATUS_PLAYBACK					0x01
#define	PDC_STATUS_RECREADY					0x02
#define	PDC_STATUS_ENDLESS					0x04
#define	PDC_STATUS_REC						0x08
#define	PDC_STATUS_SAVE						0x10
#define	PDC_STATUS_LOAD						0x20
#define	PDC_STATUS_PAUSE					0x40


/*	Trigger mode	*/
#define	PDC_TRIGGER_START					(0x00 << 24)
#define	PDC_TRIGGER_CENTER					(0x01 << 24)
#define	PDC_TRIGGER_END						(0x02 << 24)
#define	PDC_TRIGGER_RANDOM					(0x03 << 24)
#define	PDC_TRIGGER_MANUAL					(0x04 << 24)
#define	PDC_TRIGGER_RANDOM_RESET			(0x05 << 24)
#define	PDC_TRIGGER_RANDOM_CENTER			(0x06 << 24)
#define	PDC_TRIGGER_RANDOM_MANUAL			(0x07 << 24)
#define	PDC_TRIGGER_TWOSTAGE				(0x08 << 24)
#define	PDC_TRIGGER_TWOSTAGE_HALF			((0x08 << 24) | 1)
#define	PDC_TRIGGER_TWOSTAGE_QUARTER		((0x08 << 24) | 2)
#define	PDC_TRIGGER_TWOSTAGE_ONEEIGHTH		((0x08 << 24) | 3)
#define	PDC_TRIGGER_RESET					(0x09 << 24)
#define	PDC_TRIGGER_RECON_CMD				(0x10 << 24)   

/*	Sensor Gamma	*/
#define	PDC_SENSOR_GAMMA_1_0				1
#define	PDC_SENSOR_GAMMA_0_9				2
#define	PDC_SENSOR_GAMMA_0_8				3
#define	PDC_SENSOR_GAMMA_0_7				4
#define	PDC_SENSOR_GAMMA_0_6				5
#define	PDC_SENSOR_GAMMA_0_5				6
#define	PDC_SENSOR_GAMMA_0_4				7

/*	Sensor Gain	*/
#define	PDC_SENSOR_GAIN_X1					1
#define	PDC_SENSOR_GAIN_X1_5				2
#define	PDC_SENSOR_GAIN_X2					3
#define	PDC_SENSOR_GAIN_X3					4
#define	PDC_SENSOR_GAIN_X4					5
#define	PDC_SENSOR_GAIN_X6					6
#define	PDC_SENSOR_GAIN_X8					7
#define	PDC_SENSOR_GAIN_X12					8
#define	PDC_SENSOR_GAIN_X16					9
#define	PDC_SENSOR_GAIN_X24					10
#define	PDC_SENSOR_GAIN_X32					11
#define	PDC_SENSOR_GAIN_X64					12

/*	Color Temperature	*/
#define	PDC_COLORTEMP_5100K					1
#define	PDC_COLORTEMP_3100K					2
#define	PDC_COLORTEMP_USER1					3
#define	PDC_COLORTEMP_USER2					4
#define	PDC_COLORTEMP_USER3					5
#define	PDC_COLORTEMP_USER4					6

/*	Sync Priority	*/
#define	PDC_SYNCPRIORITY_OFF				0x00
#define	PDC_SYNCPRIORITY_MASTER				0x01
#define	PDC_SYNCPRIORITY_SLAVE				0x02

/*	External Input Signal	*/
#define	PDC_EXT_IN_NONE						0x01
#define	PDC_EXT_IN_CAMSYNC_POSI				0x02
#define	PDC_EXT_IN_CAMSYNC_NEGA				0x03
#define	PDC_EXT_IN_OTHERSSYNC_POSI			0x04
#define	PDC_EXT_IN_OTHERSSYNC_NEGA			0x05
#define	PDC_EXT_IN_EVENT_POSI				0x06
#define	PDC_EXT_IN_EVENT_NEGA				0x07
#define	PDC_EXT_IN_TRIGGER_POSI				0x08
#define	PDC_EXT_IN_TRIGGER_NEGA				0x09
#define	PDC_EXT_IN_READY_POSI				0x0A
#define	PDC_EXT_IN_READY_NEGA				0x0B
#define	PDC_EXT_IN_SYNC_POS					0x0C
#define	PDC_EXT_IN_SYNC_NEGA				0x0D
#define	PDC_EXT_IN_CAMSYNC					0x0E
#define	PDC_EXT_IN_OTHERSSYNC				0x0F

/* Sync In Signal */
#define	PDC_SYNC_IN_SIGNAL_NORMAL			0x01
#define	PDC_SYNC_IN_SIGNAL_NO				0x02
#define	PDC_SYNC_IN_SIGNAL_OVER				0x03

/*	External Output Signal	*/
#define	PDC_EXT_OUT_SYNC_POSI				0x01
#define	PDC_EXT_OUT_SYNC_NEGA				0x02
#define	PDC_EXT_OUT_RECORD_POSI				0x03
#define	PDC_EXT_OUT_RECORD_NEGA				0x04
#define	PDC_EXT_OUT_TRIGGER_POSI			0x05
#define	PDC_EXT_OUT_TRIGGER_NEGA			0x06
#define	PDC_EXT_OUT_READY_POSI				0x07
#define	PDC_EXT_OUT_READY_NEGA				0x08
#define	PDC_EXT_OUT_IRIG_RESET_POSI			0x09
#define	PDC_EXT_OUT_IRIG_RESET_NEGA			0x0A
#define	PDC_EXT_OUT_TTLIN_THRU_POSI			0x0B
#define	PDC_EXT_OUT_TTLIN_THRU_NEGA			0x0C
#define	PDC_EXT_OUT_EXPOSE_POSI				0x0D
#define	PDC_EXT_OUT_EXPOSE_NEGA				0x0E
#define	PDC_EXT_OUT_EXPOSE_H1_POSI			0x1D
#define	PDC_EXT_OUT_EXPOSE_H1_NEGA			0x1E
#define	PDC_EXT_OUT_EXPOSE_H2_POSI			0x2D
#define	PDC_EXT_OUT_EXPOSE_H2_NEGA			0x2E
#define	PDC_EXT_OUT_EXPOSE_H3_POSI			0x3D
#define	PDC_EXT_OUT_EXPOSE_H3_NEGA			0x3E
#define	PDC_EXT_OUT_EXPOSE_H4_POSI			0x4D
#define	PDC_EXT_OUT_EXPOSE_H4_NEGA			0x4E
#define	PDC_EXT_OUT_TRIGGER					0x50
#define	PDC_EXT_OUT_REC_POS_AND_SYNC_POS	0x51
#define	PDC_EXT_OUT_REC_POS_AND_EXPOSE_POS	0x52
#define	PDC_EXT_OUT_ODD_REC_POS_AND_SYNC_POS	0x53
#define	PDC_EXT_OUT_EVEN_REC_POS_AND_SYNC_POS	0x54
#define	PDC_EXT_OUT_ODD_REC_POS				0x55
#define	PDC_EXT_OUT_EVEN_REC_POS			0x56
#define	PDC_EXT_OUT_REC_START				0x57
#define	PDC_EXT_OUT_REC_POS_AND_EXPOSE_NEGA 0x58
#define	PDC_EXT_OUT_STRADDLING				0x59

#define	PDC_EXTIO_MAX_PORT					4

/*	Dualslope Shutter	*/
#define	PDC_DSSHUTTER_OFF					0x01
#define	PDC_DSSHUTTER_MODE1					0x02
#define	PDC_DSSHUTTER_MODE2					0x03
#define	PDC_DSSHUTTER_MODE3					0x04
#define	PDC_DSSHUTTER_VALUE_STEP5			0x11

/*	LUT	*/
#define	PDC_LUT_DEFAULT1					1
#define	PDC_LUT_DEFAULT2					2
#define	PDC_LUT_DEFAULT3					3
#define	PDC_LUT_DEFAULT4					4
#define	PDC_LUT_DEFAULT5					5
#define	PDC_LUT_DEFAULT6					6
#define	PDC_LUT_DEFAULT7					7
#define	PDC_LUT_DEFAULT8					8
#define	PDC_LUT_DEFAULT9					9
#define	PDC_LUT_DEFAULT10					10
#define	PDC_LUT_USER1						11
#define	PDC_LUT_USER2						12
#define	PDC_LUT_USER3						13
#define	PDC_LUT_USER4						14

/*	Shading	*/
#define	PDC_SHADING_OFF						1
#define	PDC_SHADING_ON						2
#define	PDC_SHADING_SAVE					3
#define	PDC_SHADING_LOAD					4
#define	PDC_SHADING_UPDATE					5
#define	PDC_SHADING_SAVE_FILE				6
#define	PDC_SHADING_LOAD_FILE				7

/*	Shading type	*/
#define	PDC_SHADING_TYPE_NORMAL				0
#define	PDC_SHADING_TYPE_FINE				1

/*	Pixel Gain	*/
#define	PDC_PIXELGAIN_OFF					0
#define	PDC_PIXELGAIN_NORMAL				1
#define	PDC_PIXELGAIN_SOFT					2
#define	PDC_PIXELGAIN_FLAT					3
#define	PDC_PIXELGAIN_SAVE					4	/*	Reserve	*/
#define	PDC_PIXELGAIN_LOAD					5	/*	Reserve	*/
#define	PDC_PIXELGAIN_SAVE_FILE				6
#define	PDC_PIXELGAIN_LOAD_FILE				7
#define	PDC_PIXELGAIN_NORMAL_64CH			8

/*	Color Plane	*/
#define	PDC_COLOR_PLANE_R					1
#define	PDC_COLOR_PLANE_G					2
#define	PDC_COLOR_PLANE_B					3

/*	I.I. Power	*/
#define	PDC_II_POWER_OFF					1
#define	PDC_II_POWER_ON						2
#define	PDC_II_POWER_ON_LOAD				3

/*	I.I. Gate Select	*/
#define	PDC_II_GATEMODE_OFF					1
#define	PDC_II_GATEMODE_CONTINUOUS			2
#define	PDC_II_GATEMODE_EXTERNAL			3
#define	PDC_II_GATEMODE_GATING				4
#define	PDC_II_GATEMODE_DELAY				5

/*	Edge Enhancement	*/
#define	PDC_EDGE_ENHANCE_OFF				1
#define	PDC_EDGE_ENHANCE_MODE1				2
#define	PDC_EDGE_ENHANCE_MODE2				3
#define	PDC_EDGE_ENHANCE_MODE3				4

/*	Video Output	*/
#define	PDC_VIDEO_OUT_VGA					0x0001
#define	PDC_VIDEO_OUT_NTSC					0x0002
#define	PDC_VIDEO_OUT_PAL					0x0003

/*	Video Output Signal	*/
#define	PDC_VIDEO_SIGNAL_VBS				0
#define	PDC_VIDEO_SIGNAL_HDSDI				1

/*	HD-SDI Mode	*/
#define	PDC_VIDEO_HDSDI_1080_60I			0
#define	PDC_VIDEO_HDSDI_1080_59_94I			1
#define	PDC_VIDEO_HDSDI_1080_50I			2
#define	PDC_VIDEO_HDSDI_1080_30P			3
#define	PDC_VIDEO_HDSDI_1080_29_97P			4
#define	PDC_VIDEO_HDSDI_1080_25P			5
#define	PDC_VIDEO_HDSDI_1080_24P			6
#define	PDC_VIDEO_HDSDI_1080_23_98P			7
#define	PDC_VIDEO_HDSDI_1080_24SF			8
#define	PDC_VIDEO_HDSDI_1080_23_98SF		9
#define	PDC_VIDEO_HDSDI_720_60P				10
#define	PDC_VIDEO_HDSDI_720_59_94P			11
#define	PDC_VIDEO_HDSDI_720_50P				12

/*	Shutter Mode	*/
#define	PDC_SHUTTERLOCK_MODE1				0
#define	PDC_SHUTTERLOCK_MODE2				1

/*	MechaShutter	*/
#define	PDC_MECHASHUTTER_MODE1				0
#define	PDC_MECHASHUTTER_MODE2				1

/*	Resolution Mode	*/
#define	PDC_RESOLUTIONLOCK_MODE1			0
#define	PDC_RESOLUTIONLOCK_MODE2			1

/*	Partition Mode	*/
#define	PDC_PARTITIONINC_MODE1				0
#define	PDC_PARTITIONINC_MODE2				1
#define	PDC_PARTITIONINC_MODE3				2

/*	8bit select	*/
#define	PDC_8BITSEL_10UPPER					2
#define	PDC_8BITSEL_10MIDDLE				1
#define	PDC_8BITSEL_10LOWER					0
#define	PDC_8BITSEL_12UPPER					4
#define	PDC_8BITSEL_12MIDDLE_U				3
#define	PDC_8BITSEL_12MIDDLE				2
#define	PDC_8BITSEL_12MIDDLE_L				1
#define	PDC_8BITSEL_12LOWER					0
#define	PDC_8BITSEL_16UPPER					8
#define	PDC_8BITSEL_8NORMAL					0

/*	Color date tranfer interleave	*/
#define	PDC_COLORDATA_NOCOLOR				0
#define	PDC_COLORDATA_INTERLEAVE_BGR		1
#define	PDC_COLORDATA_INTERLEAVE_RGB		2

/*	Gigabit-Ether I/F Parameter	*/
#define	PDC_GETHER_CONNECT_NORMAL			1
#define	PDC_GETHER_CONNECT_LOWSPEED			0
#define	PDC_GETHER_PACKETSIZE_DEFAULT		0
#define	PDC_GETHER_PACKETSIZE_LOWSPEED		722
#define	PDC_GETHER_TIMEOUT_DEFAULT			5000

/*	Detect mode	*/
#define	PDC_DETECT_NORMAL					0
#define	PDC_DETECT_AUTO						1

/*	Variable pattern num	*/
#define	PDC_VARIABLE_NUM					20

/*	Variable Free Position	*/
#define	PDC_VARIABLE_FREE_CENTER_ONLY		0x00
#define	PDC_VARIABLE_FREE_X					0x01
#define	PDC_VARIABLE_FREE_Y					0x10

/*	Signal Delay	*/
#define	PDC_DELAY_TRIGGER_IN				1
#define	PDC_DELAY_VSYNC_IN					2
#define	PDC_DELAY_GENERAL_IN				3
#define	PDC_DELAY_TRIGGER_OUT_WIDTH			4
#define	PDC_DELAY_VSYNC_OUT					5
#define	PDC_DELAY_VSYNC_OUT_WIDTH			6
#define	PDC_DELAY_EXPOSE					7
#define	PDC_DELAY_TRIGGER_MASK_WIDTH		8
#define	PDC_DELAY_VSYNC_MASK_WIDTH			9
#define	PDC_DELAY_STRADDLING_WIDTH			10
#define	PDC_DELAY_STRADDLING_DISTANCE		11

/*	Download mode	*/
#define	PDC_DOWNLOAD_MODE_VIDEO_ON			0	/*	Reserve	*/
#define	PDC_DOWNLOAD_MODE_VIDEO_OFF			1	/*	Reserve	*/
#define	PDC_DOWNLOAD_MODE_PLAYBACK_ON		0
#define	PDC_DOWNLOAD_MODE_PLAYBACK_OFF		1
#define	PDC_DOWNLOAD_MODE_LIVE_ON			2

/*	Camera mode	*/
#define	PDC_CAM_MODE_DEFAULT				0
#define	PDC_CAM_MODE_VARIABLE				1
#define	PDC_CAM_MODE_EXTERNAL				2

/*	Programmable Switch mode	*/
#define	PDC_PROGSWITCH_NONE					0
#define	PDC_PROGSWITCH_RECORDRATE_SEL		1
#define	PDC_PROGSWITCH_RESOLUTION_SEL		2
#define	PDC_PROGSWITCH_SHUTTER_SEL			3
#define	PDC_PROGSWITCH_TRIGGER_MODE_SEL		4
#define	PDC_PROGSWITCH_HEAD_SEL				5
#define	PDC_PROGSWITCH_FIT					6
#define	PDC_PROGSWITCH_STATUS				7
#define	PDC_PROGSWITCH_LIVE					8
#define	PDC_PROGSWITCH_RECREADY				9
#define	PDC_PROGSWITCH_REC					10
#define	PDC_PROGSWITCH_LOWLIGHT				11
#define	PDC_PROGSWITCH_CALIBRATE			12
#define	PDC_PROGSWITCH_OFF					13
#define	PDC_PROGSWITCH_OSD					14

#define	PDC_PROGSWITCH_MAX_NUM				4

/*	Color Bayer Convert mode	*/
#define	PDC_BAYERCONVERT_MODE1				0
#define	PDC_BAYERCONVERT_MODE2				1
#define	PDC_BAYERCONVERT_MODE3				2
#define	PDC_BAYERCONVERT_MODE4				3

/*	Sync Out Times	*/
#define	PDC_SYNCOUT_TIMES_X1				1
#define	PDC_SYNCOUT_TIMES_X2				2
#define	PDC_SYNCOUT_TIMES_X4				4
#define	PDC_SYNCOUT_TIMES_X6				6
#define	PDC_SYNCOUT_TIMES_X8				8
#define	PDC_SYNCOUT_TIMES_X10				10
#define	PDC_SYNCOUT_TIMES_X20				20
#define	PDC_SYNCOUT_TIMES_X30				30
#define	PDC_SYNCOUT_TIMES_X0_5				101
#define	PDC_SYNCOUT_TIMES_X1_3				102
#define	PDC_SYNCOUT_TIMES_X1_4				103
#define	PDC_SYNCOUT_TIMES_X1_5				104
#define	PDC_SYNCOUT_TIMES_X1_6				105
#define	PDC_SYNCOUT_TIMES_X1_7				106
#define	PDC_SYNCOUT_TIMES_X1_8				107
#define	PDC_SYNCOUT_TIMES_X1_9				108
#define	PDC_SYNCOUT_TIMES_X1_10				109
#define	PDC_SYNCOUT_TIMES_X1_11				110
#define	PDC_SYNCOUT_TIMES_X1_12				111
#define	PDC_SYNCOUT_TIMES_X1_13				112
#define	PDC_SYNCOUT_TIMES_X1_14				113
#define	PDC_SYNCOUT_TIMES_X1_15				114

/*	Exposure Out Times	*/
#define	PDC_EXPOSEOUT_TIMES_X1				1

#define	PDC_EXPOSEOUT_TIMES_X0_5				101
#define	PDC_EXPOSEOUT_TIMES_X1_3				102
#define	PDC_EXPOSEOUT_TIMES_X1_4				103
#define	PDC_EXPOSEOUT_TIMES_X1_5				104
#define	PDC_EXPOSEOUT_TIMES_X1_6				105
#define	PDC_EXPOSEOUT_TIMES_X1_7				106
#define	PDC_EXPOSEOUT_TIMES_X1_8				107
#define	PDC_EXPOSEOUT_TIMES_X1_9				108
#define	PDC_EXPOSEOUT_TIMES_X1_10				109
#define	PDC_EXPOSEOUT_TIMES_X1_11				110
#define	PDC_EXPOSEOUT_TIMES_X1_12				111
#define	PDC_EXPOSEOUT_TIMES_X1_13				112
#define	PDC_EXPOSEOUT_TIMES_X1_14				113
#define	PDC_EXPOSEOUT_TIMES_X1_15				114

#define	PDC_REC_EXPOSEOUT_TIMES_X1				1
#define PDC_REC_EXPOSEOUT_TIMES_X1_10			101
#define	PDC_REC_EXPOSEOUT_TIMES_X1_100			102
#define PDC_REC_EXPOSEOUT_TIMES_X1_200			103
#define PDC_REC_EXPOSEOUT_TIMES_X1_300			104
#define PDC_REC_EXPOSEOUT_TIMES_X1_400			105
#define PDC_REC_EXPOSEOUT_TIMES_X1_500			106
#define PDC_REC_EXPOSEOUT_TIMES_X1_600			107
#define PDC_REC_EXPOSEOUT_TIMES_X1_700			108
#define PDC_REC_EXPOSEOUT_TIMES_X1_800			109
#define PDC_REC_EXPOSEOUT_TIMES_X1_900			110
#define PDC_REC_EXPOSEOUT_TIMES_X1_1000			111

/*	Store Preset	*/
#define	PDC_STORE_PRESET_1					1
#define	PDC_STORE_PRESET_2					2
#define	PDC_STORE_PRESET_3					3
#define	PDC_STORE_PRESET_4					4

/*	Color Enhancement	*/
#define	PDC_COLOR_ENHANCE_OFF				0
#define	PDC_COLOR_ENHANCE_X0_5				1
#define	PDC_COLOR_ENHANCE_X1				2
#define	PDC_COLOR_ENHANCE_X1_5				3
#define	PDC_COLOR_ENHANCE_X2				4

/*	Ethernet	*/
#define	PDC_ETHER_INFO_IP_ADDRESS			0
#define	PDC_ETHER_INFO_NETMASK				1
#define	PDC_ETHER_INFO_GATEWAY				2
#define	PDC_ETHER_INFO_DHCP					3

/*	Head Type	*/
#define	PDC_HEADTYPE_MONO					0
#define	PDC_HEADTYPE_COLOR					1
#define	PDC_HEADTYPE_II						2
#define	PDC_HEADTYPE_UNKNOWN				0xFF

/*	Auto Play	*/
#define	PDC_AUTOPLAY_OFF					0
#define	PDC_AUTOPLAY_MEMORY_MODE			1
#define	PDC_AUTOPLAY_ON						2

/*	CameraLink	*/
#define	PDC_CAM_STATUS_DEFAULT				0
#define	PDC_CAM_STATUS_POW_CAB_NOT_CONNECT	1
#define	PDC_CAM_STATUS_CAM_NOT_CONNECT		2
#define	PDC_CAM_STATUS_CL_CONNECT			3
#define	PDC_CAM_STATUS_POCL_CONNECT			4

/*	Live resolution		*/
#define	PDC_LIVE_RESO_FULL					0
#define	PDC_LIVE_RESO_HALF					1
#define PDC_LIVE_RESO_3						2
#define	PDC_LIVE_RESO_QUARTER				3
#define PDC_LIVE_RESO_5						4
#define PDC_LIVE_RESO_6						5
#define PDC_LIVE_RESO_7						6
#define	PDC_LIVE_RESO_DQUARTER				7

/*	Baudrate	*/
#define PDC_BAUDRATE_38400					0
#define PDC_BAUDRATE_19200					1
#define PDC_BAUDRATE_9600					2

/*	AVI Compress dialog	*/
#define	PDC_COMPRESS_DIALOG_HIDE			0
#define	PDC_COMPRESS_DIALOG_SHOW			1

/*	Recording type	*/
#define	PDC_RECORDING_TYPE_READY_AND_TRIG	0
#define	PDC_RECORDING_TYPE_DIRECT_TRIG		1
#define	PDC_RECORDING_TYPE_DIRECT_START		2

/*	MCDL Data Mode	*/
#define PDC_MCDL_DATA_MODE1					0
#define PDC_MCDL_DATA_MODE2					1

/* 	Display Mode with drawing function */
#define PDC_DISPLAY_RESO_FULL				0
#define PDC_DISPLAY_RESO_HALF				1
#define PDC_DISPLAY_RESO_QUARTER			2

/*	High Speed Mode	*/
#define	PDC_HIGHSPEED_MODE_NORMAL			0
#define	PDC_HIGHSPEED_MODE_HIGH				1
#define	PDC_HIGHSPEED_MODE_SUPERHIGH		2

/*	High Speed Mode List	*/
#define	PDC_HIGHSPEED_NORMAL_150K			0x00009600
#define	PDC_HIGHSPEED_HIGH_675K				0x0002A301
#define	PDC_HIGHSPEED_SUPERHIGH_775K		0x00030702
#define	PDC_HIGHSPEED_SUPERHIGH_1000K		0x0003E802
#define	PDC_HIGHSPEED_SUPERHIGH_1300K		0x00051402
#define	PDC_HIGHSPEED_SUPERHIGH_1550K		0x00060E02
#define	PDC_HIGHSPEED_NORMAL_259K			0x0A010300
#define	PDC_HIGHSPEED_HIGH_259K				0x0C010351
#define	PDC_HIGHSPEED_NORMAL_324K			0x0A014400
#define	PDC_HIGHSPEED_HIGH_324K				0x0C014451
#define	PDC_HIGHSPEED_NORMAL_480K			0x0A01E000
#define	PDC_HIGHSPEED_HIGH_480K				0x0C01E051
#define	PDC_HIGHSPEED_NORMAL_900K			0x0A038400
#define	PDC_HIGHSPEED_HIGH_900K				0x0C038451
#define	PDC_HIGHSPEED_NORMAL_1080K			0x0A043800
#define	PDC_HIGHSPEED_HIGH_1080K			0x0C043851
#define	PDC_HIGHSPEED_NORMAL_256K			0x00010000
#define	PDC_HIGHSPEED_HIGH_800K				0x00032001

#define	PDC_HIGHSPEED_NORMAL_240K			0x0A00F000
#define	PDC_HIGHSPEED_HIGH_240K				0x0C00F051
#define	PDC_HIGHSPEED_NORMAL_288K			0x0A012000
#define	PDC_HIGHSPEED_HIGH_288K				0x0C012051
#define	PDC_HIGHSPEED_NORMAL_2100K			0x0A083400
#define	PDC_HIGHSPEED_HIGH_2100K			0x0C083451

/*  Instruction Set  */
#define PDC_INSTSET_NONE					0x80000000
#define PDC_INSTSET_AUTO					0x40000000
#define PDC_INSTSET_MMX						0x00000001
#define PDC_INSTSET_SSE2					0x00000002

#define PDC_INSTSET_DEFAULT					PDC_INSTSET_NONE	/*	The initial state of device	*/

/*	Bayer Alignment */
#define PDC_BAYER_ALIGNMENT_RGGB 0
#define PDC_BAYER_ALIGNMENT_BGGR 1
#define PDC_BAYER_ALIGNMENT_GRBG 2
#define PDC_BAYER_ALIGNMENT_GBRG 3

/*	Polarization Pattern	*/
#define	PDC_POLARIZATION_PATTERN_1	1
#define	PDC_POLARIZATION_PATTERN_2	2
#define	PDC_POLARIZATION_PATTERN_3	3
#define	PDC_POLARIZATION_PATTERN_4	4

/*	Degree of Polarizer	*/
#define	PDC_POLARIZER_DEGREE_0		1
#define	PDC_POLARIZER_DEGREE_45		2
#define	PDC_POLARIZER_DEGREE_90		3
#define	PDC_POLARIZER_DEGREE_135	4

/*	Colormap Index	*/
#define	PDC_POLARIZATION_COLORMAP_180	1
#define	PDC_POLARIZATION_COLORMAP_90	2
#define	PDC_POLARIZATION_COLORMAP_45	4
#define	PDC_POLARIZATION_COLORMAP_30	6

/*	RESOLUTION_MODE	*/
#define	PDC_RESOLUTION_STANDARD_MODE	0
#define	PDC_RESOLUTION_VALIABLE_MODE	1

/*	Bit Depth Mode of MRAW File	*/
#define	PDC_MRAW_BITDEPTH_8		0
#define	PDC_MRAW_BITDEPTH_10	1
#define	PDC_MRAW_BITDEPTH_12	2
#define	PDC_MRAW_BITDEPTH_16	3

/*	Bit Depth Mode of RAW File	*/
#define PDC_RAW_BITDEPTH_8		0
#define PDC_RAW_BITDEPTH_16		1

/*	Effective Bit	*/
#define	PDC_EFFECTIVE_BITS_HIGH		0
#define	PDC_EFFECTIVE_BITS_LOW		1

/*	FrameNumber	*/
#define	PDC_ILLEGAL_FRAME_NUMBER	0xFFFFFFFFL

/*	KEYPAD COMMAND	*/
#define PDC_KEYPAD_COMMAND_FRAMERATE_UP		0
#define PDC_KEYPAD_COMMAND_FRAMERATE_DOWN	1
#define PDC_KEYPAD_COMMAND_RESOLUTION_UP	2
#define PDC_KEYPAD_COMMAND_RESOLUTION_DOWN	3
#define PDC_KEYPAD_COMMAND_SHUTTER_UP		4
#define PDC_KEYPAD_COMMAND_SHUTTER_DOWN		5
#define PDC_KEYPAD_COMMAND_TRIGGER_UP		6
#define PDC_KEYPAD_COMMAND_TRIGGER_DOWN		7
#define PDC_KEYPAD_COMMAND_LIVE_MEM			8
#define PDC_KEYPAD_COMMAND_PLAYBACK_FR		9
#define PDC_KEYPAD_COMMAND_PLAYBACK_REV		10
#define PDC_KEYPAD_COMMAND_PLAYBACK_PLAY	11
#define PDC_KEYPAD_COMMAND_PLAYBACK_FF		12
#define PDC_KEYPAD_COMMAND_PLAYBACK_PAUSE	13
#define PDC_KEYPAD_COMMAND_PLAYBACK_STOP	14
#define PDC_KEYPAD_COMMAND_SEGMENT_START	15
#define PDC_KEYPAD_COMMAND_SEGMENT_END		16
#define PDC_KEYPAD_COMMAND_SEGMENT_ON_OFF	17
#define PDC_KEYPAD_COMMAND_REC_READY		18
#define PDC_KEYPAD_COMMAND_REC				19
#define PDC_KEYPAD_COMMAND_STORE			20
#define PDC_KEYPAD_COMMAND_MENU				21
#define PDC_KEYPAD_COMMAND_ENTER			22
#define PDC_KEYPAD_COMMAND_ZOOM				23
#define PDC_KEYPAD_COMMAND_FIT_SAMESIZE		24
#define PDC_KEYPAD_COMMAND_ARROW_UP			25
#define PDC_KEYPAD_COMMAND_ARROW_DOWN		26
#define PDC_KEYPAD_COMMAND_ARROW_LEFT		27
#define PDC_KEYPAD_COMMAND_ARROW_RIGHT		28
#define PDC_KEYPAD_COMMAND_BACK				29
#define PDC_KEYPAD_COMMAND_SCROLL			30
#define PDC_KEYPAD_COMMAND_CALIBRATE		31
#define PDC_KEYPAD_COMMAND_STATUS			32
#define PDC_KEYPAD_COMMAND_PRESET1			33
#define PDC_KEYPAD_COMMAND_PRESET2			34
#define PDC_KEYPAD_COMMAND_PRESET3			35
#define PDC_KEYPAD_COMMAND_PRESET4			36
#define PDC_KEYPAD_COMMAND_FUNCTION			37
#define PDC_KEYPAD_COMMAND_LOWLIGHT			38

/*	Black Clip Level	*/
#define	PDC_BLACK_CLIP_LEVEL_OFF			0
#define	PDC_BLACK_CLIP_LEVEL_1				1
#define	PDC_BLACK_CLIP_LEVEL_2				2
#define	PDC_BLACK_CLIP_LEVEL_3				3
#define	PDC_BLACK_CLIP_LEVEL_4				4
#define	PDC_BLACK_CLIP_LEVEL_5				5
#define	PDC_BLACK_CLIP_LEVEL_6				6
#define	PDC_BLACK_CLIP_LEVEL_7				7
#define	PDC_BLACK_CLIP_LEVEL_8				8

/*	Expose Extension	*/
#define	PDC_EXPOSE_EXTENSION_INCLUDED		0
#define	PDC_EXPOSE_EXTENSION_EXCLUDED		1

/*	FPGA CONFIG STATUS	*/
#define	PDC_FPGA_CONFIG_BUFFER_FILE_LOADING 0
#define	PDC_FPGA_CONFIG_ERASING				1
#define	PDC_FPGA_CONFIG_PROGRAMMING			2
#define	PDC_FPGA_CONFIG_VERIFYING			3

/*	REGISTER_SETTING_TYPE	*/
#define	PDC_REGISTER_SETTING_MAIN			0
#define	PDC_REGISTER_SETTING_SUB			1
#define	PDC_REGISTER_SETTING_HEAD1			2
#define	PDC_REGISTER_SETTING_HEAD2			3

/*	RECORD BIT SELECT	*/
#define PDC_RECBITSEL_8_12UPPER			0x00010000
#define PDC_RECBITSEL_8_12MIDDLE_U		0x00010001
#define PDC_RECBITSEL_8_12MIDDLE		0x00010002
#define PDC_RECBITSEL_8_12MIDDLE_L		0x00010003
#define PDC_RECBITSEL_8_12LOWER			0x00010004

#define PDC_SHUTTER_DISPLAY_VIRTUAL			0
#define PDC_SHUTTER_DISPLAY_REAL			1

/*	Lens Control	*/
#define	PDC_LENS_CONTROL_OFF				0
#define	PDC_LENS_CONTROL_EF					1
#define	PDC_LENS_CONTROL_MYUTRON			2

/*	GETH TRANSFER MODE */
#define PDC_GETH_TRANSFER_STANDARDSPEED			0
#define PDC_GETH_TRANSFER_LOWSPEED				1

/*	FAN CONTROL	*/
#define	PDC_FAN_CTRL_OFF				0x00000000
#define	PDC_FAN_CTRL_ON					0x00000001

/*	FAN USED			*/
#define	PDC_FAN_NOT_USED					0
#define	PDC_FAN_USED						1
#define	PDC_FAN_NOT_USED_ALL			0x00000000
/*	FAN STATE			*/
#define	PDC_FAN_STATE_NORMAL				0
#define	PDC_FAN_STATE_STOP					1
#define	PDC_FAN_STATE_STOP_ALL			0x00000000

/*	FAN CTRL STATE		*/
#define	PDC_FAN_CTRL_STATE_ON				0
#define	PDC_FAN_CTRL_STATE_OFF				1
#define	PDC_FAN_CTRL_STATE_FORCED_ON		2

/*	SD CARD SLOT		*/
#define	PDC_SD_CARD_SLOT_1				0x00000000
#define	PDC_SD_CARD_SLOT_2				0x00000001

/*	SD CARD IN/OUT		*/
#define	PDC_SD_CARD_OUT					0x00000000
#define	PDC_SD_CARD_IN					0x00000001

/*	SD CARD WRITE PROTECT	*/
#define	PDC_SD_CARD_WP_OFF				0x00000000
#define	PDC_SD_CARD_WP_ON				0x00000001

/*	SD CARD FORMAT ENABLED	*/
#define	PDC_SD_CARD_FORMAT_DISABLED		0x00000000
#define	PDC_SD_CARD_FORMAT_ENABLED		0x00000001

/*	SD CARD SPEED MODE		*/
#define	PDC_SD_CARD_SPEED_MODE_DEF		0x00000000
#define	PDC_SD_CARD_SPEED_MODE_HIGH		0x40000000
#define	PDC_SD_CARD_SPEED_MODE_SDR12	0x80000000
#define	PDC_SD_CARD_SPEED_MODE_SDR25	0x80000001
#define	PDC_SD_CARD_SPEED_MODE_SDR50	0x80000002
#define	PDC_SD_CARD_SPEED_MODE_SDR104	0x80000003
#define	PDC_SD_CARD_SPEED_MODE_DDR50	0x80000004

/*	SD CARD SPEED CLASS		*/
#define	PDC_SD_CARD_SPEED_CLASS_2		0x00000002
#define	PDC_SD_CARD_SPEED_CLASS_4		0x00000004
#define	PDC_SD_CARD_SPEED_CLASS_6		0x00000006
#define	PDC_SD_CARD_SPEED_CLASS_10		0x0000000A

/*	SD CARD DATA COUNT		*/
#define	PDC_SD_CARD_DATA_CNT_MAX			32

/*	SD CARD MEMORY MODE		*/
#define	PDC_SD_CARD_MEM_MODE_NORMAL		0x00000000
#define	PDC_SD_CARD_MEM_MODE_FIT		0x00000001

/*	SD CARD RUN STATE	1	*/
#define	PDC_SD_CARD_RUN_STATE_IDLE		0x00000000
#define	PDC_SD_CARD_RUN_STATE_RUN		0x00000001
#define	PDC_SD_CARD_RUN_STATE_ERROR		0x00000002
#define	PDC_SD_CARD_RUN_STATE_CANCEL	0x00000003

/*	SD CARD SAVE ERROR*/
#define	PDC_SD_CARD_SAVE_ERR_OK				0
#define	PDC_SD_CARD_SAVE_ERR_CMD			-1
#define	PDC_SD_CARD_SAVE_ERR_SIZE			-2
#define	PDC_SD_CARD_SAVE_ERR_SLOT			-3
#define	PDC_SD_CARD_SAVE_ERR_FORMAT			-6

/*	SENSOR AMP VOLTAGE ADJUST ERROR	*/
#define	PDC_SEN_AMP_V_ADJUST_ERR_OK 	0x00000000
#define	PDC_SEN_AMP_V_ADJUST_ERR_AMP	0x00000001
#define	PDC_SEN_AMP_V_ADJUST_ERR_IMAGE	0x00000002
#define	PDC_SEN_AMP_V_ADJUST_ERR_CMD	0x00000003

#endif	/*	_PDC_VALUE_H_	*/



