// this content is regenerated by 'Pre-Build Event.py' whenever file 'svnrevision.txt' does not exist or it's content is not actual
//
// Generated file - DO NOT EDIT !!!
//
#ifndef KYFGLIB_VERSION_H_
#define KYFGLIB_VERSION_H_

#define KYFGLIB_MAJOR_VERSION 5
#define KYFGLIB_MINOR_VERSION 2
#define KYFGLIB_PATCH_VERSION 0

#define KYFGLIB_VERSION (KYFGLIB_MAJOR_VERSION*10000 + KYFGLIB_MINOR_VERSION*100 + KYFGLIB_PATCH_VERSION)

// Non-zero value indicates a "Beta build"
#define KYFGLIB_BETA 0

// Non-zero value indicates a "Release Candidate build"
#define KYFGLIB_RC 0

#endif  // KYFGLIB_VERSION_H_


